[project]
name = "islamic-ai-assistant"
version = "0.1.0"
description = "Islamic multi-agents assitant that help you live a better life as Muslim"
authors = [
    {name = "hOuajdi"}
]
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "torch (>=2.11.0,<3.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "pandas (>=3.0.2,<4.0.0)",
    "huggingface-hub (>=1.11.0,<2.0.0)",
    "kagglehub (>=1.0.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
